# Generated by Django 4.2.8 on 2024-01-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_material_productmaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaterial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='productmaterial',
            name='product',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='ProductMaterial',
        ),
    ]
