# Generated by Django 4.2.8 on 2024-01-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0005_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
