# Generated by Django 4.2.8 on 2024-01-17 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0007_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
